package net.casual.championships.uhc

import net.casual.arcade.utils.ComponentUtils.withFont
import net.casual.championships.common.util.CommonComponents.constant
import net.minecraft.network.chat.Component

object UHCComponents {
    private val UHC_FONT = UHCMod.id("bitmap_font")

    val CASUAL_UHC get() = Component.literal("Casual UHC")

    val TITLE get() = Component.literal("\ue000").withFont(UHC_FONT)

    val ADVANCEMENT_ROOT by constant("uhc.advancements.root")
    val ADVANCEMENT_ROOT_DESC by constant("uhc.advancements.root.desc")
    val ADVANCEMENT_FIRST_BLOOD by constant("uhc.advancements.firstBlood")
    val ADVANCEMENT_FIRST_BLOOD_DESC by constant("uhc.advancements.firstBlood.desc")
    val ADVANCEMENT_EARLY_EXIT by constant("uhc.advancements.earlyExit")
    val ADVANCEMENT_EARLY_EXIT_DESC by constant("uhc.advancements.earlyExit.desc")
    val ADVANCEMENT_MOSTLY_HARMLESS by constant("uhc.advancements.mostlyHarmless")
    val ADVANCEMENT_MOSTLY_HARMLESS_DESC by constant("uhc.advancements.mostlyHarmless.desc")
    val ADVANCEMENT_HEAVY_HITTER by constant("uhc.advancements.heavyHitter")
    val ADVANCEMENT_HEAVY_HITTER_DESC by constant("uhc.advancements.heavyHitter.desc")
    val ADVANCEMENT_WINNER by constant("uhc.advancements.winner")
    val ADVANCEMENT_WINNER_DESC by constant("uhc.advancements.winner.desc")
    val ADVANCEMENT_COMBAT_LOGGER by constant("uhc.advancements.combatLogger")
    val ADVANCEMENT_COMBAT_LOGGER_DESC by constant("uhc.advancements.combatLogger.desc")
    val ADVANCEMENT_NOT_DUSTLESS by constant("uhc.advancements.notDustless")
    val ADVANCEMENT_NOT_DUSTLESS_DESC by constant("uhc.advancements.notDustless.desc")
    val ADVANCEMENT_PARKOUR_MASTER by constant("uhc.advancements.parkourMaster")
    val ADVANCEMENT_PARKOUR_MASTER_DESC by constant("uhc.advancements.parkourMaster.desc")
    val ADVANCEMENT_WORLD_RECORD_PACE by constant("uhc.advancements.worldRecordPace")
    val ADVANCEMENT_WORLD_RECORD_PACE_DESC by constant("uhc.advancements.worldRecordPace.desc")
    val ADVANCEMENT_EMBARRASSING by constant("uhc.advancements.thatsEmbarrassing")
    val ADVANCEMENT_EMBARRASSING_DESC by constant("uhc.advancements.thatsEmbarrassing.desc")
    val ADVANCEMENT_BUSTED by constant("uhc.advancements.busted")
    val ADVANCEMENT_BUSTED_DESC by constant("uhc.advancements.busted.desc")
    val ADVANCEMENT_DEMOLITION_EXPERT by constant("uhc.advancements.demolitionExpert")
    val ADVANCEMENT_DEMOLITION_EXPERT_DESC by constant("uhc.advancements.demolitionExpert.desc")
    val ADVANCEMENT_WE_BELIEVE by constant("uhc.advancements.okWeBelieveYouNow")
    val ADVANCEMENT_WE_BELIEVE_DESC by constant("uhc.advancements.okWeBelieveYouNow.desc")
    val ADVANCEMENT_FALLING_BLOCK by constant("uhc.advancements.fallingBlock")
    val ADVANCEMENT_FALLING_BLOCK_DESC by constant("uhc.advancements.fallingBlock.desc")
    val ADVANCEMENT_DREAM_LUCK by constant("uhc.advancements.dreamLuck")
    val ADVANCEMENT_DREAM_LUCK_DESC by constant("uhc.advancements.dreamLuck.desc")
    val ADVANCEMENT_BROKEN_ANKLES by constant("uhc.advancements.brokenAnkles")
    val ADVANCEMENT_BROKEN_ANKLES_DESC by constant("uhc.advancements.brokenAnkles.desc")
    val ADVANCEMENT_ON_THE_EDGE by constant("uhc.advancements.onTheEdge")
    val ADVANCEMENT_ON_THE_EDGE_DESC by constant("uhc.advancements.onTheEdge.desc")
    val ADVANCEMENT_SKILL_ISSUE by constant("uhc.advancements.skillIssue")
    val ADVANCEMENT_SKILL_ISSUE_DESC by constant("uhc.advancements.skillIssue.desc")
    val ADVANCEMENT_SOLOIST by constant("uhc.advancements.soloist")
    val ADVANCEMENT_SOLOIST_DESC by constant("uhc.advancements.soloist.desc")
    val ADVANCEMENT_NOT_NOW by constant("uhc.advancements.notNow")
    val ADVANCEMENT_NOT_NOW_DESC by constant("uhc.advancements.notNow.desc")
    val ADVANCEMENT_KATIE by constant("uhc.advancements.ldap")
    val ADVANCEMENT_KATIE_DESC by constant("uhc.advancements.ldap.desc")
    val ADVANCEMENT_BORED by constant("uhc.advancements.officiallyBored")
    val ADVANCEMENT_BORED_DESC by constant("uhc.advancements.officiallyBored.desc")
    val ADVANCEMENT_DISTRACTED by constant("uhc.advancements.distracted")
    val ADVANCEMENT_DISTRACTED_DESC by constant("uhc.advancements.distracted.desc")
    val ADVANCEMENT_FIND_THE_BUTTON by constant("uhc.advancements.findTheButton")
    val ADVANCEMENT_FIND_THE_BUTTON_DESC by constant("uhc.advancements.findTheButton.desc")
    val ADVANCEMENT_UH_OH by constant("uhc.advancements.uhOh")
    val ADVANCEMENT_UH_OH_DESC by constant("uhc.advancements.uhOh.desc")
    val ADVANCEMENT_BASICALLY by constant("uhc.advancements.basically")
    val ADVANCEMENT_BASICALLY_DESC by constant("uhc.advancements.basically.desc")
    val ADVANCEMENT_TEAM_PLAYER by constant("uhc.advancements.teamPlayer")
    val ADVANCEMENT_TEAM_PLAYER_DESC by constant("uhc.advancements.teamPlayer.desc")
    val ADVANCEMENT_LAST_MAN by constant("uhc.advancements.lastManStanding")
    val ADVANCEMENT_LAST_MAN_DESC by constant("uhc.advancements.lastManStanding.desc")
    val ADVANCEMENT_BEAR_CARED by constant("uhc.advancements.bearCared")
    val ADVANCEMENT_BEAR_CARED_DESC by constant("uhc.advancements.bearCared.desc")

    val BROADCAST_HOSTED_BY by constant("uhc.broadcast.hostedBy")
    val BROADCAST_BORDER_WARNING by constant("uhc.broadcast.borderWarning")
    val BROADCAST_SPECTATING by constant("uhc.broadcast.spectator")
    val BROADCAST_NO_POTIONS by constant("uhc.broadcast.noPotions")
    val BROADCAST_GLOBAL_CHAT by constant("uhc.broadcast.globalChat")
    val BROADCAST_NIGHT_VISION by constant("uhc.broadcast.nightVision")
    val BROADCAST_TEAM_GLOW by constant("uhc.broadcast.teamGlow")
    val BROADCAST_MINESWEEPER by constant("uhc.broadcast.minesweeper")
    val BROADCAST_RULES by constant("uhc.broadcast.rules")
    val BROADCAST_S_COMMAND by constant("uhc.broadcast.specCommand")
    val BROADCAST_PLAYER_HEADS by constant("uhc.broadcast.playerHeads")
    val BROADCAST_REMOVE_ME by constant("uhc.broadcast.joke")
}