[versions]
minecraft       = "1.21.11"
fabric-loader   = "0.18.2"
parchment       = "1.21.10:2025.10.12"
fabric-api      = "0.139.4+1.21.11"
fabric-kotlin   = "1.13.7+kotlin.2.2.21"
map-canvas      = "0.6.0+1.21.9"
arcade          = "0.8.1-beta.33+1.21.11"
casual-database = "0.3.1"
voicechat-api   = "2.6.0"
permissions     = "0.6.1"

# Plugins
fabric-loom = "1.14-SNAPSHOT"

[libraries]
minecraft       = { module = "com.mojang:minecraft"                        , version.ref = "minecraft" }
fabric-loader   = { module = "net.fabricmc:fabric-loader"                  , version.ref = "fabric-loader" }
fabric-api      = { module = "net.fabricmc.fabric-api:fabric-api"          , version.ref = "fabric-api" }
fabric-kotlin   = { module = "net.fabricmc:fabric-language-kotlin"         , version.ref = "fabric-kotlin" }
map-canvas      = { module = "eu.pb4:map-canvas-api"                       , version.ref = "map-canvas" }
arcade          = { module = "net.casualchampionships:arcade"              , version.ref = "arcade" }
arcade-datagen  = { module = "net.casualchampionships:arcade-datagen"      , version.ref = "arcade" }
casual-database = { module = "net.casualchampionships:casual-database-core", version.ref = "casual-database" }
voicechat-api   = { module = "de.maxhenkel.voicechat:voicechat-api"        , version.ref = "voicechat-api" }
permissions     = { module = "me.lucko:fabric-permissions-api"             , version.ref = "permissions" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }