[versions]
minecraft       = "26.3"
kotlin          = "2.4.20"
fabric-loader   = "0.19.5"
fabric-api      = "0.161.0+26.3"
fabric-kotlin   = "1.14.1+kotlin.2.4.20"
map-canvas      = "0.9.0+26.2"
polymer         = "0.18.2+26.3"
arcade          = "0.14.0-beta.8+26.3"
casual-database = "0.3.2"
voicechat-api   = "2.6.24"

# Plugins
fabric-loom = "1.18-SNAPSHOT"
joystick    = "1.0.4"

[libraries]
minecraft       = { module = "com.mojang:minecraft"                        , version.ref = "minecraft" }
fabric-loader   = { module = "net.fabricmc:fabric-loader"                  , version.ref = "fabric-loader" }
fabric-api      = { module = "net.fabricmc.fabric-api:fabric-api"          , version.ref = "fabric-api" }
fabric-kotlin   = { module = "net.fabricmc:fabric-language-kotlin"         , version.ref = "fabric-kotlin" }
map-canvas      = { module = "eu.pb4:map-canvas-api"                       , version.ref = "map-canvas" }
polymer-core    = { module = "eu.pb4:polymer-core"                         , version.ref = "polymer" }
casual-database = { module = "net.casualchampionships:casual-database-core", version.ref = "casual-database" }
voicechat-api   = { module = "de.maxhenkel.voicechat:voicechat-api"        , version.ref = "voicechat-api" }

[plugins]
kotlin-jvm           = { id = "org.jetbrains.kotlin.jvm"                 , version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
fabric-loom          = { id = "net.fabricmc.fabric-loom"                 , version.ref = "fabric-loom" }
joystick             = { id = "net.casualchampionships.joystick"         , version.ref = "joystick" }